-- MySQL Script generated by MySQL Workbench
-- Thu Mar 16 07:18:30 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS
, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS
, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE
, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA
IF NOT EXISTS `mydb` DEFAULT CHARACTER
SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `mydb`
;

-- -----------------------------------------------------
-- Table `mydb`.`estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estudiante`
(
  `id de identificacion` INT NOT NULL,
  `nombre` VARCHAR
(30) NOT NULL,
  `correro electronico` VARCHAR
(30) NOT NULL,
  `programa academico` VARCHAR
(60) NOT NULL,
  `cuatrimestre` INT NOT NULL,
  PRIMARY KEY
(`id de identificacion`),
  UNIQUE INDEX `id de identificacion_UNIQUE`
(`id de identificacion` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lider`
-- -----------------------------------------------------
CREATE TABLE
IF NOT EXISTS `mydb`.`lider`
(
  `id del lider` INT NOT NULL,
  `correo` VARCHAR
(45) NOT NULL,
  PRIMARY KEY
(`id del lider`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`facultad de ingenieria`
-- -----------------------------------------------------
CREATE TABLE
IF NOT EXISTS `mydb`.`facultad de ingenieria`
(
  `idfacultad de ingenieria` INT NOT NULL,
  `carrera` VARCHAR
(70) NOT NULL,
  PRIMARY KEY
(`idfacultad de ingenieria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Solicitud`
-- -----------------------------------------------------
CREATE TABLE
IF NOT EXISTS `mydb`.`Solicitud`
(
  `id` INT NOT NULL,
  `tipo de solicitud` VARCHAR
(45) NOT NULL,
  `lider_id del lider` INT NOT NULL,
  `facultad de ingenieria_idfacultad de ingenieria` INT NOT NULL,
  `facultad de ingenieria_idfacultad de ingenieria1` INT NOT NULL,
  PRIMARY KEY
(`id`),
  INDEX `fk_Solicitud_lider1_idx`
(`lider_id del lider` ASC) VISIBLE,
  INDEX `fk_Solicitud_facultad de ingenieria1_idx`
(`facultad de ingenieria_idfacultad de ingenieria` ASC) VISIBLE,
  INDEX `fk_Solicitud_facultad de ingenieria2_idx`
(`facultad de ingenieria_idfacultad de ingenieria1` ASC) VISIBLE,
  CONSTRAINT `fk_Solicitud_lider1`
    FOREIGN KEY
(`lider_id del lider`)
    REFERENCES `mydb`.`lider`
(`id del lider`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION,
  CONSTRAINT `fk_Solicitud_facultad de ingenieria1
`
    FOREIGN KEY
(`facultad de ingenieria_idfacultad de ingenieria`)
    REFERENCES `mydb`.`facultad de ingenieria`
(`idfacultad de ingenieria`)
    ON
DELETE NO ACTION,
    ON
UPDATE NO ACTION,
  CONSTRAINT `fk_Solicitud_facultad de ingenieria2
`
    FOREIGN KEY
(`facultad de ingenieria_idfacultad de ingenieria1`)
    REFERENCES `mydb`.`facultad de ingenieria`
(`idfacultad de ingenieria`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estudiante_has_Solicitud`
-- -----------------------------------------------------
CREATE TABLE
IF NOT EXISTS `mydb`.`estudiante_has_Solicitud`
(
  `estudiante_id de identificacion` INT NOT NULL,
  `Solicitud_id` INT NOT NULL,
  PRIMARY KEY
(`estudiante_id de identificacion`, `Solicitud_id`),
  INDEX `fk_estudiante_has_Solicitud_Solicitud1_idx`
(`Solicitud_id` ASC) VISIBLE,
  INDEX `fk_estudiante_has_Solicitud_estudiante_idx`
(`estudiante_id de identificacion` ASC) VISIBLE,
  CONSTRAINT `fk_estudiante_has_Solicitud_estudiante`
    FOREIGN KEY
(`estudiante_id de identificacion`)
    REFERENCES `mydb`.`estudiante`
(`id de identificacion`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION,
  CONSTRAINT `fk_estudiante_has_Solicitud_Solicitud1`
    FOREIGN KEY
(`Solicitud_id`)
    REFERENCES `mydb`.`Solicitud`
(`id`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`resultados`
-- -----------------------------------------------------
CREATE TABLE
IF NOT EXISTS `mydb`.`resultados`
(
  `idresultados` INT NOT NULL,
  `aprobados` INT NOT NULL,
  `pendiente` INT NOT NULL,
  PRIMARY KEY
(`idresultados`),
  UNIQUE INDEX `idresultados_UNIQUE`
(`idresultados` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Solicitud_has_resultados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Solicitud_has_resultados`
(
  `Solicitud_id` INT NOT NULL,
  `resultados_idresultados` INT NOT NULL,
  PRIMARY KEY
(`Solicitud_id`, `resultados_idresultados`),
  INDEX `fk_Solicitud_has_resultados_resultados1_idx`
(`resultados_idresultados` ASC) VISIBLE,
  INDEX `fk_Solicitud_has_resultados_Solicitud1_idx`
(`Solicitud_id` ASC) VISIBLE,
  CONSTRAINT `fk_Solicitud_has_resultados_Solicitud1`
    FOREIGN KEY
(`Solicitud_id`)
    REFERENCES `mydb`.`Solicitud`
(`id`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION,
  CONSTRAINT `fk_Solicitud_has_resultados_resultados1`
    FOREIGN KEY
(`resultados_idresultados`)
    REFERENCES `mydb`.`resultados`
(`idresultados`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE
=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS
=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS
=@OLD_UNIQUE_CHECKS;
